server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.0.140
    ip-address: 192.168.0.140
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.140:8761/eureka/,http://192.168.0.141:8761/eureka/,http://192.168.0.142:8761/eureka/
