server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.0.49
    ip-address: 192.168.0.49
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.0.49:8761/eureka/  #,http://192.168.0.142:8761/eureka/
