server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.219.135
    ip-address: 192.168.219.135
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.219.135:8761/eureka/  #,http://192.168.0.142:8761/eureka/
